version: '3'

services:
  api:
    container_name: api
    command: /sbin/init
    build: ./docker
    ports:
      - 8801:8000
    privileged: true
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./src/:/var/www/html/
